import { Kitchen, Meal, User, Order, Subscription, SubscriptionPlan } from '../models/types';

// Mock Users
export const MOCK_USER: User = {
    id: 'u1',
    name: 'Hameed Isaam',
    email: 'hameed@example.com',
    phone: '+91 98765 43210',
    addresses: [
        { id: 'a1', label: 'Home', fullAddress: '123, Green Park, New Delhi' },
        { id: 'a2', label: 'Office', fullAddress: 'Tech Hub, Cyber City, Gurugram' },
        { id: 'a3', label: 'Parents Home', fullAddress: '45, Old Lane, Jaipur' },
    ],
    role: 'user',
};

// Mock Meals
const meals: Meal[] = [
    {
        id: 'm1',
        kitchenId: 'k1',
        name: 'Home-style Thali',
        description: 'Dal, Rice, 2 Rotis, Seasonal Veg, Salad',
        price: 150,
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: true,
    },
    {
        id: 'm2',
        kitchenId: 'k1',
        name: 'Aloo Paratha Combo',
        description: '2 Parathas, Curd, Pickle',
        price: 120,
        image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Breakfast',
        isVegetarian: true,
    },
    {
        id: 'm3',
        kitchenId: 'k2',
        name: 'Chicken Curry Meal',
        description: 'Chicken Curry, Rice, Roti',
        price: 200,
        image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: false,
    },
    {
        id: 'm4',
        kitchenId: 'k3',
        name: 'Healthy Salad Bowl',
        description: 'Mixed greens, quinoa, tofu, light dressing',
        price: 180,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: true,
    },
    {
        id: 'm5',
        kitchenId: 'k4',
        name: 'Masala Dosa',
        description: 'Crispy rice crepe with potato filling and chutneys',
        price: 100,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Breakfast',
        isVegetarian: true,
    },
    {
        id: 'm6',
        kitchenId: 'k5',
        name: 'Margherita Pizza',
        description: 'Classic tomato, mozzarella, and basil',
        price: 350,
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: true,
    },
    {
        id: 'm7',
        kitchenId: 'k6',
        name: 'Sushi Platter',
        description: 'Assorted fresh sushi rolls with wasabi',
        price: 450,
        image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: false,
    },
    {
        id: 'm8',
        kitchenId: 'k7',
        name: 'Gourmet Burger',
        description: 'Juicy patty, cheddar, caramelized onions, fries',
        price: 250,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: false,
    },
    {
        id: 'm9',
        kitchenId: 'k8',
        name: 'Chocolate Lava Cake',
        description: 'Warm chocolate cake with molten center',
        price: 180,
        image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: true,
    },
    {
        id: 'm10',
        kitchenId: 'k9',
        name: 'Steamed Dumplings',
        description: 'Chicken or veg dumplings with spicy dip',
        price: 220,
        image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Snack',
        isVegetarian: false,
    },
    {
        id: 'm11',
        kitchenId: 'k10',
        name: 'Hyderabadi Biryani',
        description: 'Aromatic rice with spices and tender meat',
        price: 350,
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: false,
    },
    {
        id: 'm12',
        kitchenId: 'k11',
        name: 'Crispy Tacos',
        description: '3 hard-shell tacos with salsa and guacamole',
        price: 280,
        image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Snack',
        isVegetarian: false,
    },
    {
        id: 'm13',
        kitchenId: 'k12',
        name: 'Creamy Alfredo Pasta',
        description: 'Penne pasta in rich white sauce',
        price: 320,
        image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: true,
    },
    {
        id: 'm14', // Note: Renumbering logic might be off if I don't check prev. Just appending.
        kitchenId: 'k14',
        name: 'Spicy Miso Ramen',
        description: 'Rich miso broth with chashu pork and egg',
        price: 450,
        image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: false,
    },
    {
        id: 'm15',
        kitchenId: 'k15',
        name: 'Fruit & Nut Gelato',
        description: '3 scoops of premium italian ice cream',
        price: 250,
        image: 'https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Snack',
        isVegetarian: true,
    },
    {
        id: 'm16',
        kitchenId: 'k16',
        name: 'Turkey Club Sub',
        description: 'Fresh turkey, lettuce, tomato, cheese',
        price: 200,
        image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: false,
    },
    {
        id: 'm17',
        kitchenId: 'k17',
        name: 'Samosa Chaat',
        description: 'Crushed samosas with chutneys and yogurt',
        price: 120,
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Snack',
        isVegetarian: true,
    },
    {
        id: 'm18',
        kitchenId: 'k18',
        name: 'Chicken Gyro Wrap',
        description: 'Grilled chicken, tzatziki, veggies in pita',
        price: 220,
        image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&fit=crop&auto=format&q=80',
        type: 'Lunch',
        isVegetarian: false,
    },
    {
        id: 'm19',
        kitchenId: 'k19',
        name: 'Grilled Salmon',
        description: 'Fresh salmon fillet with asparagus and lemon butter',
        price: 550,
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: false,
    },
    {
        id: 'm20',
        kitchenId: 'k20',
        name: 'BBQ Pork Ribs',
        description: 'Slow-cooked smoked ribs with BBQ sauce and coleslaw',
        price: 480,
        image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Dinner',
        isVegetarian: false,
    },
    {
        id: 'm21',
        kitchenId: 'k21',
        name: 'Falafel Platter',
        description: 'Crispy falafels, hummus, pita, and tabbouleh',
        price: 260,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: true,
    },
    {
        id: 'm22',
        kitchenId: 'k22',
        name: 'Blueberry Pancakes',
        description: 'Stack of fluffy pancakes with syrup and fresh berries',
        price: 190,
        image: 'https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Breakfast',
        isVegetarian: true,
    },
    {
        id: 'm23',
        kitchenId: 'k23',
        name: 'Buddha Bowl',
        description: 'Quinoa, avocado, roasted chickpeas, and tahini dressing',
        price: 240,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
        type: 'Lunch',
        isVegetarian: true,
    },
];

// Mock Kitchens
export const MOCK_KITCHENS: Kitchen[] = [
    {
        id: 'k8',
        name: 'Sweet Tooth Haven',
        rating: 4.8,
        cuisine: ['Desserts', 'Bakery'],
        imageUrl: meals[8].image,
        deliveryTime: '15-25 min',
        verified: true,
        menu: [meals[8]], // Cake
    },
    {
        id: 's1',
        name: 'Aunty\'s Tiffin Service',
        rating: 4.8,
        cuisine: ['Home Food', 'North Indian'],
        imageUrl: meals[0].image, // Thali
        deliveryTime: 'Pre-scheduled',
        verified: true,
        isSubscription: true,
        menu: [meals[0], meals[1]],
    },
    {
        id: 's2',
        name: 'Sharma Ji Home Kitchen',
        rating: 4.6,
        cuisine: ['Pure Veg', 'Thali'],
        imageUrl: meals[1].image, // Paratha
        deliveryTime: 'Pre-scheduled',
        verified: true,
        isSubscription: true,
        menu: [meals[1], meals[4]],
    },
    {
        id: 's3',
        name: 'FitBite Home Meals',
        rating: 4.9,
        cuisine: ['Healthy', 'Salads'],
        imageUrl: meals[3].image, // Salad
        deliveryTime: 'Pre-scheduled',
        verified: true,
        isSubscription: true,
        menu: [meals[3], meals[22]],
    },
    {
        id: 's4',
        name: 'South Taste Tiffins',
        rating: 4.7,
        cuisine: ['South Indian', 'Home Food'],
        imageUrl: meals[4].image, // Dosa
        deliveryTime: 'Pre-scheduled',
        verified: true,
        isSubscription: true,
        menu: [meals[4], meals[10]],
    },
    {
        id: 'k2',
        name: 'Mom\'s Magic',
        rating: 4.5,
        cuisine: ['Indian', 'Healthy'],
        imageUrl: meals[2].image,
        deliveryTime: '25-40 min',
        verified: true,
        menu: [meals[2]],
    },
    {
        id: 'k3',
        name: 'Green Bowl',
        rating: 4.9,
        cuisine: ['Salads', 'Healthy'],
        imageUrl: meals[3].image,
        deliveryTime: '20-30 min',
        verified: true,
        menu: [meals[3]],
    },
    {
        id: 'k4',
        name: 'South Spice Route',
        rating: 4.7,
        cuisine: ['South Indian', 'Dosa'],
        imageUrl: meals[4].image,
        deliveryTime: '25-35 min',
        verified: true,
        menu: [meals[4]], // Masala Dosa
    },
    {
        id: 'k5',
        name: 'Pizza Paradiso',
        rating: 4.6,
        cuisine: ['Italian', 'Pizza'],
        imageUrl: meals[5].image,
        deliveryTime: '35-50 min',
        verified: true,
        menu: [meals[5]], // Pizza
    },
    {
        id: 'k6',
        name: 'Sushi Zen',
        rating: 4.9,
        cuisine: ['Japanese', 'Sushi'],
        imageUrl: meals[6].image,
        deliveryTime: '40-60 min',
        verified: false,
        menu: [meals[6]], // Sushi
    },
    {
        id: 'k7',
        name: 'Burger Bistro',
        rating: 4.4,
        cuisine: ['American', 'Fast Food'],
        imageUrl: meals[7].image,
        deliveryTime: '20-30 min',
        verified: true,
        menu: [meals[7]], // Burger
    },
    {
        id: 'k1',
        name: 'Golden Spoon Residency',
        rating: 4.6,
        cuisine: ['North Indian', 'Mughlai'],
        imageUrl: meals[0].image,
        deliveryTime: '35-50 min',
        verified: true,
        menu: [meals[0], meals[1]],
    },
    {
        id: 'k9',
        name: 'The Wok House',
        rating: 4.7,
        cuisine: ['Chinese', 'Asian'],
        imageUrl: meals[9].image,
        deliveryTime: '30-45 min',
        verified: true,
        menu: [meals[9]], // Dumplings
    },
    {
        id: 'k10',
        name: 'Biryani Blues',
        rating: 4.5,
        cuisine: ['Biryani', 'Mughlai'],
        imageUrl: meals[10].image,
        deliveryTime: '40-55 min',
        verified: true,
        menu: [meals[10]], // Biryani
    },
    {
        id: 'k11',
        name: 'Taco Fiesta',
        rating: 4.6,
        cuisine: ['Mexican', 'Tacos'],
        imageUrl: meals[11].image,
        deliveryTime: '25-40 min',
        verified: false,
        menu: [meals[11]], // Tacos
    },
    {
        id: 'k12',
        name: 'Pasta Point',
        rating: 4.8,
        cuisine: ['Italian', 'Pasta'],
        imageUrl: meals[12].image,
        deliveryTime: '35-45 min',
        verified: true,
        menu: [meals[12]], // Pasta
    },
    {
        id: 'k13',
        name: 'Bean & Brew',
        rating: 4.9,
        cuisine: ['Cafe', 'Coffee'],
        imageUrl: meals[8].image,
        deliveryTime: '15-25 min',
        verified: true,
        menu: [meals[8]], // Cake re-use
    },
    {
        id: 'k14',
        name: 'Tokyo Ramen',
        rating: 4.8,
        cuisine: ['Japanese', 'Ramen'],
        imageUrl: meals[13].image,
        deliveryTime: '35-50 min',
        verified: true,
        menu: [meals[13]], // Ramen
    },
    {
        id: 'k15',
        name: 'Gelato Bliss',
        rating: 4.9,
        cuisine: ['Ice Cream', 'Dessert'],
        imageUrl: meals[14].image,
        deliveryTime: '15-25 min',
        verified: true,
        menu: [meals[14]], // Gelato
    },
    {
        id: 'k16',
        name: 'Fresh Subs',
        rating: 4.3,
        cuisine: ['Sandwiches', 'Fast Food'],
        imageUrl: meals[15].image,
        deliveryTime: '20-30 min',
        verified: false,
        menu: [meals[15]],
    },
    {
        id: 'k17',
        name: 'Desi Chaat House',
        rating: 4.7,
        cuisine: ['Street Food', 'Indian'],
        imageUrl: meals[16].image,
        deliveryTime: '25-35 min',
        verified: true,
        menu: [meals[16]],
    },
    {
        id: 'k18',
        name: 'Greek Gyros',
        rating: 4.6,
        cuisine: ['Mediterranean', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&fit=crop&auto=format&q=80', // Known good BBQ/Meat photo
        deliveryTime: '30-40 min',
        verified: true,
        menu: [meals[17]],
    },
    {
        id: 'k19',
        name: 'Ocean Catch',
        rating: 4.8,
        cuisine: ['Seafood', 'Grill'],
        imageUrl: meals[18].image,
        deliveryTime: '40-55 min',
        verified: true,
        menu: [meals[18]],
    },
    {
        id: 'k20',
        name: 'Smokehouse BBQ',
        rating: 4.7,
        cuisine: ['American', 'BBQ'],
        imageUrl: meals[19].image,
        deliveryTime: '45-60 min',
        verified: true,
        menu: [meals[19]],
    },
    {
        id: 'k21',
        name: 'Arabian Nights',
        rating: 4.5,
        cuisine: ['Middle Eastern', 'Arabian'],
        imageUrl: meals[20].image,
        deliveryTime: '30-45 min',
        verified: true,
        menu: [meals[20]],
    },
    {
        id: 'k22',
        name: 'Morning Glory',
        rating: 4.9,
        cuisine: ['Breakfast', 'Pancakes'],
        imageUrl: meals[21].image,
        deliveryTime: '20-30 min',
        verified: true,
        menu: [meals[21]], // Pancakes
    },
    {
        id: 'k24',
        name: 'Thai Garden',
        rating: 4.7,
        cuisine: ['Thai', 'Asian'],
        imageUrl: meals[22].image,
        deliveryTime: '35-50 min',
        verified: true,
        menu: [meals[22]],
    },
    {
        id: 'k25',
        name: 'K-Street Korean BBQ',
        rating: 4.8,
        cuisine: ['Korean', 'BBQ'],
        imageUrl: meals[19].image,
        deliveryTime: '40-55 min',
        verified: true,
        menu: [meals[19]],
    },
    {
        id: 'k26',
        name: 'Beirut Bites',
        rating: 4.6,
        cuisine: ['Lebanese', 'Middle Eastern'],
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&fit=crop&auto=format&q=80', // Known good Falafel photo
        deliveryTime: '30-45 min',
        verified: true,
        menu: [meals[20]],
    },
    {
        id: 's5',
        name: 'Bake My Day Subscriptions',
        rating: 4.9,
        cuisine: ['Bakery', 'Desserts'],
        imageUrl: meals[8].image, // Chocolate Cake
        deliveryTime: 'Daily Morning',
        verified: true,
        isSubscription: true,
        menu: [meals[8], meals[21]], // Cake, Pancakes
    },
    {
        id: 's6',
        name: 'Mediterranean Magic Prep',
        rating: 4.8,
        cuisine: ['Healthy', 'Middle Eastern'],
        imageUrl: meals[20].image, // Falafel
        deliveryTime: 'Pre-scheduled',
        verified: true,
        isSubscription: true,
        menu: [meals[20]],
    },
    {
        id: 's7',
        name: 'Protein Power Meals',
        rating: 4.7,
        cuisine: ['High Protein', 'Keto'],
        imageUrl: meals[18].image, // Grilled Salmon
        deliveryTime: 'Pre-scheduled',
        verified: true,
        isSubscription: true,
        menu: [meals[18], meals[2]], // Salmon, Chicken Curry
    }
];

// Mock Subscription Plans
export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
    {
        id: 'weekly',
        name: 'Weekly Plan',
        durationDays: 7,
        price: 999,
        description: 'Perfect for trial. 7 days of delicious meals.',
    },
    {
        id: 'monthly',
        name: 'Monthly Plan',
        durationDays: 30,
        price: 3499,
        description: 'Best value. Hassle-free food for the whole month.',
    },
];

export const MOCK_ORDERS: Order[] = [
    {
        id: 'o1',
        userId: 'u1',
        kitchenId: 'k1',
        items: [{ mealId: 'm1', quantity: 1 }],
        totalAmount: 150,
        status: 'Delivered',
        createdAt: new Date(Date.now() - 86400000).toISOString(), // Yesterday
        deliveryAddressId: 'a1',
    },
    {
        id: 'o2',
        userId: 'u1',
        kitchenId: 'k1',
        items: [{ mealId: 'm2', quantity: 2 }],
        totalAmount: 240,
        status: 'Preparing', // Active order
        createdAt: new Date().toISOString(),
        deliveryAddressId: 'a2',
    }
];
